version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0

executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/browsers:node14.17.0-chrome88-ff89"

workflows:
  vue-cli-3-ct:
    jobs:
      - cypress/install:
          name: "Setup Vue CLI 3"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "vue-cli-3/package.json" }}
          working_directory: vue-cli-3
          yarn: true
          executor: with-chrome-and-firefox

      - cypress/run:
          name: "Run Vue CLI 3 Component Tests"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "vue-cli-3/package.json" }}
          working_directory: vue-cli-3
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:8080"
          yarn: true
          start: yarn serve
          command: yarn cypress run-ct
          timeout: 3m
          requires:
            - "Setup Vue CLI 3"
  vue-cli-2-ct:
    jobs:
      - cypress/install:
          name: "Setup Vue CLI 2"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "vue-cli-2/package.json" }}
          working_directory: vue-cli-2
          yarn: true
          executor: with-chrome-and-firefox

      - cypress/run:
          name: "Run Vue CLI 2 Component Tests"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "vue-cli-2/package.json" }}
          working_directory: vue-cli-2
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:8080"
          yarn: true
          start: yarn serve
          command: yarn cypress run-ct
          timeout: 3m
          requires:
            - "Setup Vue CLI 2"
  vite-vue-ct:
    jobs:
      - cypress/install:
          name: "Setup Vite Vue"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "vite-vue/package.json" }}
          working_directory: vite-vue
          yarn: true
          executor: with-chrome-and-firefox
          build: "yarn build"

      - cypress/run:
          name: "Run Vite Vue Component Tests"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "vite-vue/package.json" }}
          working_directory: vite-vue
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:5000"
          yarn: true
          start: yarn serve
          command: yarn cypress run-ct
          timeout: 3m
          requires:
            - "Setup Vite Vue"
  vite-react-ct:
    jobs:
      - cypress/install:
          name: "Setup Vite React"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "vite-react/package.json" }}
          working_directory: vite-react
          yarn: true
          executor: with-chrome-and-firefox
          build: "yarn build"

      - cypress/run:
          name: "Run Vite React Component Tests"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "vite-react/package.json" }}
          working_directory: vite-react
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:5000"
          yarn: true
          start: yarn serve
          command: yarn cypress run-ct
          timeout: 3m
          requires:
            - "Setup Vite React"
  create-react-app-ct:
    jobs:
      - cypress/install:
          name: "Setup Create React App"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "create-react-app/package.json" }}
          working_directory: create-react-app
          yarn: true
          executor: with-chrome-and-firefox

      - cypress/run:
          name: "Run Create React App Component Tests"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "create-react-app/package.json" }}
          working_directory: create-react-app
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start
          command: yarn cypress run-ct
          timeout: 3m
          requires:
            - "Setup Create React App"
  create-react-app-react-router-ct:
    jobs:
      - cypress/install:
          name: "Setup Create React App React Router"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "create-react-app-react-router/package.json" }}
          working_directory: create-react-app-react-router
          yarn: true
          executor: with-chrome-and-firefox

      - cypress/run:
          name: "Run Create React App React Router Component Tests"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "create-react-app-react-router/package.json" }}
          working_directory: create-react-app-react-router
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start
          command: yarn cypress run-ct
          timeout: 3m
          requires:
            - "Setup Create React App React Router"
  create-react-app-redux-ct:
    jobs:
      - cypress/install:
          name: "Setup Create React App Redux"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "create-react-app-redux/package.json" }}
          working_directory: create-react-app-redux
          yarn: true
          executor: with-chrome-and-firefox

      - cypress/run:
          name: "Run Create React App Redux Component Tests"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "create-react-app-redux/package.json" }}
          working_directory: create-react-app-redux
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start
          command: yarn cypress run-ct
          timeout: 3m
          requires:
            - "Setup Create React App Redux"
  create-react-app-tailwind-ct:
    jobs:
      - cypress/install:
          name: "Setup Create React App Tailwind"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "create-react-app-tailwind/package.json" }}
          working_directory: create-react-app-tailwind
          yarn: true
          executor: with-chrome-and-firefox

      - cypress/run:
          name: "Run Create React App Tailwind Component Tests"
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "create-react-app-tailwind/package.json" }}
          working_directory: create-react-app-tailwind
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start
          command: yarn cypress run-ct
          timeout: 3m
          requires:
            - "Setup Create React App Tailwind"